### ISSUE TITLE
Tab loses focus when it's title is edited

### ISSUE THREAD

**Issue by FriederHannenheim** [Adanos020/egui_dock#158]
**Describe the bug**
I have a TextEdit in a tab which edits the tab title. When I enter a letter, the text edit loses focus and I need to click it again to edit

**Expected behavior**
The text edit works fine

EDIT: Forgot to mention that the Tab in TabViewer is **not** the title

**Comment by FriederHannenheim** [comment]
Example code:

Cargo.toml:
```toml
[package]
name = "egui_dock_example"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eframe = "0.22.0"
egui = "0.22.0"
egui_dock = "0.6.3"
```
```rust
use std::collections::HashMap;

use eframe::egui;
use egui_dock::{NodeIndex, Style, Tree};

fn main() {
    let native_options = eframe::NativeOptions::default();
    eframe::run_native("My egui App", native_options, Box::new(|cc| Box::new(MyEguiApp::new(cc)))).unwrap();
}

#[derive(Default)]
struct MyEguiApp {
    tree: Tree<String>,
    tab_viewer: TabViewer,
}

impl MyEguiApp {
    fn new(cc: &eframe::CreationContext<'_>) -> Self {
        let tab1 = "tab1".to_string();
        let tree = Tree::new(vec![tab1]);
        Self { 
            tree, 
            tab_viewer: TabViewer {
                tab_names: HashMap::from([("tab1".to_string(), "cool tab".to_string())])
            }
        }
    }
}

impl eframe::App for MyEguiApp {
   fn update(&mut self, ctx: &egui::Context, frame: &mut eframe::Frame) {
       egui::CentralPanel::default().show(ctx, |ui| {
            egui_dock::DockArea::new(&mut self.tree)
                .style(Style::from_egui(ui.style().as_ref()))
                .show_inside(ui, &mut self.tab_viewer);
       });
   }
}

#[derive(Default)]
struct TabViewer {
    pub tab_names: HashMap<String, String>,
}

impl egui_dock::TabViewer for TabViewer {
    type Tab = String;

    fn ui(&mut self, ui: &mut egui::Ui, tab: &mut Self::Tab) {
        ui.text_edit_singleline(self.tab_names.get_mut(tab).unwrap());
    }

    fn title(&mut self, tab: &mut Self::Tab) -> egui::WidgetText {
        self.tab_names[tab].clone().into()
    }
}
```
